package fin;

import java.util.regex.Pattern;
import fin.Group;


public enum Categorie {
	KONTOAUSGLEICH(Group.IGNORE),
	HINNERBAECKER(Group.IGNORE),
	UNTERHALT_YUNA(Group.CONSTANT,"(DE16250501801912152665)"),
	UNTERHALT_SOHEE(Group.CONSTANT, "(Ehegattenunterhalt)|(KWON)|(Yuna)"),
	
	UNTERHALT_MILADY(Group.CONSTANT, "Haushalt"),
	MILADY_OTHER(Group.CONSTANT, "MILADY"),
	FOURTH(Group.CONSTANT),
	MIETE(Group.CONSTANT, "(DOERNBERG)|(DORNBERG)"),
	STROM(Group.CONSTANT),
	MOBIL_RALPH_YUNA(Group.VARIABLE, "(1159828)|(1053225986)"),
	MOBIL_MILADY(Group.VARIABLE, "2110520"),
	FESTNETZ(Group.CONSTANT, "(DE06631240) | (FESTNETZ)|(UNITYMEDIA)|(VODAFONE)"),
	ZAHNARZT(Group.CONSTANT, "(HROMADN)"), 
	EINKOMMEN(Group.IGNORE, "(HAYS)|(QUESTAX)"),
	WEISSER (Group.CONSTANT),	
	VGF(Group.CONSTANT),
	KONTOAUSGLEICH1(Group.IGNORE, "(MLP CARD Konto)|(KONTOAUSGLEICH)|(MASTERCA )"),
	WEDDING(Group.PAST, "( DKK )|(Borgerservice)|(KOEHL)|(KREISVERWALTUNGSREF)|(NOA NOA)"),
	GELDAUTOMAT(Group.VARIABLE, "(GA NR)|(Kartennutzung )|(MLPCASH)"),
	JANITOS(Group.CONSTANT),
	RETOUREN(Group.IGNORE),
	CARE_CONCEPT(Group.PAST),
	EBAY(Group.VARIABLE),
	SYNGENIO(Group.INCOME),
	IMAC(Group.PAST,"DISKO"),  
	HEIDELBERGER(Group.CONSTANT),
	HALLESCHE(Group.CONSTANT),
	CONDOR(Group.CONSTANT, "CONDOR"),OSTERHOLZER(Group.CONSTANT),
	DAZIAN(Group.CONSTANT),
	SCHUMANNSTR(Group.CONSTANT, "(WEG SCHUMANNSTR)|(GRUNDSTEUER B)"),
	FRASPA(Group.CONSTANT, "(5201130454)|(5201130500)|(TILGUNG)"),
	BAHN(Group.VARIABLE,"(DEUTSCHE BAHN)|(DB VERTRIEB)|(MVG AUTOMAT)"),
	PAYPAL(Group.VARIABLE),
	AMAZON(Group.VARIABLE),
	SO_HEE_EXTRA(Group.PAST,"(ABRECHNUNG ANLAGE U)|(KWON)"),
	BENZIN(Group.VARIABLE, "(TANK)|(SHELL)|(HEM-)|(ARAL)|(GREBE)|(ESSO)|( OMV )"),
	HAUSHALT(Group.IGNORE),
	UMSATZSTEUER(Group.IGNORE, "(UMS\\.ST)|(UMS\\.)|(umsst\\.)"), 
	FINANZAMT(Group.IGNORE, "(FINANZKASSE)|(FINANZAMT)|(FK MÜNCHEN)|(WILHELMSTRASSE)|(EINKOMMENSTEUER)|(05861)"),
	ABSCHLUSS(Group.CONSTANT, "Abschluss lt[.] Anlage"),
	EINZUG_KREDITKARTE(Group.IGNORE,"EINZUGSERMAECHTIGUNG PN:1975 MLP CARD"),
	EXTRAENERGIE(Group.CONSTANT),
	QUELLENSTEUER(Group.CONSTANT, "(Kapitalertragsteuer)|(Solid.-Zuschlag)"),
	CONCERT(Group.VARIABLE, "(MUENCHENMUSIK)|(DOMSPATZEN)|(TICKET)"),
	KRAFTFAHRT_VERSICHERUNG(Group.PAST, "(KRAFTFAHRT-VERSICHERUNG) | (FreeYou)"),
	HAFTPFLICHT(Group.PAST),
	UMZUG(Group.PAST,"(JOBRUF)"),
	MILADY_PKV(Group.PAST,"IMB-CONSULT"),
	KLAUS_DIETER_FRANK(Group.PAST),
	MINERO(Group.PAST),
	VATI(Group.PAST,"(E[.] WERCHNER)|(EBERHARD)"),
	STANDARD_LIFE(Group.PAST),
	RESTAURANT(Group.VARIABLE,"(RESTAURANT)|(TEQUILA)|(NASCA CAFE GMBH)"),
	INNINGS(Group.CONSTANT),
	TD_BANK(Group.VARIABLE, "(siehe Anlage 1 PN:935)|(ZAHLUNG IN DAS AUSLAND)"),
	ARZT(Group.VARIABLE, "(TPZ MÜNCHEN SÜD)|(ORTHOPÄDIE)"),
	APOTHEKE(Group.VARIABLE),
	DEPARTMENT_STORE(Group.VARIABLE, "(FUNDGRUBE)|(H&M)|(HIEBER)|(GALERIA)|(HUGENDUBEL)|(PINAKOTHEK)|(MOTHER EARTH)|(ZARA)|(PERLENSHOP)|(DALLMAYR)|(KARSTADT)|(IKEA)|(ROLLER)|(TOOM)|( VINOS )|(PRAKTIKER)|(MÜLLER)|(DROGERIEMARKT)|(BUCHHANDLUNG)"),
	SCHUFA_HOLDING(Group.PAST),
	VOLKSHOCHSCHULE(Group.VARIABLE),
	GMX(Group.CONSTANT, "GMBH-GMX"),
	GEZ(Group.CONSTANT, "( GEZ )|(Rundfunk)"),
	FAMILY_SUPPORT(Group.VARIABLE, "(RAQUEL BATISTA POLANCO)|(ERICK FERNANDEZ)"),
	EINKOMMENSTEUER(Group.IGNORE,"(31117)"),
	GROCERIES(Group.VARIABLE,"(NAHKAUF)|(REWE)|(PENNY)|(V-MARKT)|(TENGELMANN)|(GRUENER MARKT)|(ALDI)|(HIT)|(LIDL)|(ORIENT SHOP)|(VITALIA)|(HONGKONG MARKET)"),
	UNCLASSIFIED(Group.UNCLASSIEFIED, "");


	public Group getGroup() {
		return group;
	}

	private final Pattern pattern;
	private final Group group;

	Categorie(Group group, String regex) {
		this.group = group;
		this.pattern = Pattern.compile(".*(" + regex.toUpperCase() + ").*");
	}
	Categorie(Group group) {
		this.group = group;
		this.pattern = Pattern.compile(".*(" + this.name().toUpperCase().replace('_', '.') + ").*");
	}

	public Pattern getPattern() {
		return pattern;
	}

}
